#  vim:ts=4:sts=4:sw=4:et
#
#  Author: Hari Sekhon
#  Date: Tue May 26 10:39:01 UTC 2015
#
#  https://github.com/harisekhon/spark-apps
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#  to help improve or steer this or other code I publish
#
#  http://www.linkedin.com/in/harisekhon
#

language: scala
jdk:
  - oraclejdk8
  - oraclejdk7
#  - openjdk6

scala:
  # no dep available for org.elasticsearch#elasticsearch-spark_2.9.3;2.1.0.Beta4
  #- 2.9.3
  - 2.10.4
  # "Scala 2.11 support in Spark does not support a few features due to dependencies which are themselves not Scala 2.11 ready. Specifically, Spark's external Kafka library and JDBC component are not yet supported in Scala 2.11 builds."
  # See https://spark.apache.org/docs/latest/building-spark.html for updates on this
  #- 2.11.2
# This will follow make to ensure that we have built the Java submodule library required as an SBT unmanaged dep
before_install:
  - make

sudo: required

notifications:
  email: false

script:
  - make test

services:
  - elasticsearch

env:
  global:
    - ELASTICSEARCH_HOST=localhost
    - ELASTICSEARCH_INDEX=myIndex
    - ELASTICSEARCH_TYPE=myType
